### ISSUE TITLE
"Cannot subtract b from a because b is larger than a" despite no explicit underflow

### ISSUE THREAD

**Issue by Rudxain** [rust-num/num-bigint#256]
[This is the issue](https://github.com/Rudxain/ackermann.rs/issues/1) (full panic-message included there), and [this is the permalink to the latest commit](https://github.com/Rudxain/ackermann.rs/blob/a17573f9cbe95477cd4a9ee9d1156f2758124b26/src/lib.rs) (at the time of writing this)

**Comment by cuviper** [comment]
I don't know what you mean by "despite no explicit underflow". `BigUint` cannot represent negative numbers, so subtracting any `a - b` requires `a >= b`. You can set `RUST_BACKTRACE=1` to help find where the subtraction came from.

**Comment by Rudxain** [comment]
Ok, I'm going to post the backtrace and do more rigorous debugging.

This bug is very weird because I've read the source many times, and every subtraction has checks for `0`, so it *should never* underflow.

**Comment by Rudxain** [comment]
The problems seems to be in my `pow`, but the only "subtraction" would be the comparison in the loop.

Output of `export RUST_BACKTRACE=full; cargo run -- 3 0`:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/ackmn 3 0 2`
thread 'main' panicked at 'Cannot subtract b from a because b is larger than a.', /home/rudxain/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.3/src/biguint/subtraction.rs:69:5
stack backtrace:
   0:     0x55ad221ddc3d - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ad221ddc3d - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ad221ddc3d - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55ad221ddc3d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55ad221f840c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x55ad221dbdf1 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x55ad221df315 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55ad221df315 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55ad221df315 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x55ad221df031 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x55ad221df8a6 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x55ad221bbf28 - std::panicking::begin_panic::{{closure}}::h1d06e6719238583a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:617:9
  12:     0x55ad221bbdb9 - std::sys_common::backtrace::__rust_end_short_backtrace::hf80b4e19cb1de253
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55ad221bbe73 - std::panicking::begin_panic::h2e13425f6f8f781c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:616:12
  14:     0x55ad221c5db6 - num_bigint::biguint::subtraction::sub2::hd7d03a59af55fe28
                               at /home/rudxain/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.3/src/biguint/subtraction.rs:69:5
  15:     0x55ad221a4885 - num_bigint::biguint::subtraction::<impl core::ops::arith::SubAssign<&num_bigint::biguint::BigUint> for num_bigint::biguint::BigUint>::sub_assign::h8c9a812363c41180
                               at /home/rudxain/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.3/src/biguint/subtraction.rs:121:9
  16:     0x55ad221a47b4 - num_bigint::biguint::subtraction::<impl core::ops::arith::Sub<&num_bigint::biguint::BigUint> for num_bigint::biguint::BigUint>::sub::h1b6871b9e5dd0333
                               at /home/rudxain/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.3/src/biguint/subtraction.rs:115:9
  17:     0x55ad2219ff98 - ackermann::A::he360776e28ee50c4
                               at /home/rudxain/GitHub/ackermann.rs/src/lib.rs:132:2
  18:     0x55ad2219c030 - ackmn::main::hdee3937d86cf13dc
                               at /home/rudxain/GitHub/ackermann.rs/src/main.rs:63:17
  19:     0x55ad2219d56b - core::ops::function::FnOnce::call_once::h8b48c70c4d3d857e
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  20:     0x55ad2219d10e - std::sys_common::backtrace::__rust_begin_short_backtrace::h70c28757c5339ae1
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:122:18
  21:     0x55ad2219f281 - std::rt::lang_start::{{closure}}::hbd9e35504e5631de
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:145:18
  22:     0x55ad221d8dce - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  23:     0x55ad221d8dce - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  24:     0x55ad221d8dce - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  25:     0x55ad221d8dce - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  26:     0x55ad221d8dce - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  27:     0x55ad221d8dce - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  28:     0x55ad221d8dce - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  29:     0x55ad221d8dce - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  30:     0x55ad221d8dce - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  31:     0x55ad2219f250 - std::rt::lang_start::h835aa8322a97f923
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:144:17
  32:     0x55ad2219c18c - main
  33:     0x7fe7c9e1dd90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  34:     0x7fe7c9e1de40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  35:     0x55ad2219a925 - _start
  36:                0x0 - <unknown>

```

**Comment by cuviper** [comment]
It looks like the main possibility was `exp == 0` when you subtract `exp -= &n1;` -- which you've now ruled out with an earlier zero check. So you're all better now?

**Comment by Rudxain** [comment]
I still need to do some more testing and debugging to determine the exact cause. I've "patched" the bug by falling back to the `pow` method when `exp` fits in a `u32`, but the bug isn't fixed yet. The `exp -= &n1` seems like the most reasonable culprit (as you said)

**Comment by Rudxain** [comment]
[Finally fixed!](https://github.com/Rudxain/ackermann.rs/commit/bc8c37196fa024a74e70bcddaa0a59027c22e238). I forgot to multiply by `b` at the return of `pow`

**Comment by Rudxain** [comment]
BTW, I promise I will do more effort debugging and reading source-code (both mine and from this), and reading docs, before opening an Issue. I'm really sorry for the inconveniences I may have caused. I was being more incompetent lately, my brain was "on autopilot" for some reason these days

**Comment by cuviper** [comment]
Thanks, I'm glad you found your bug!
